# Vue Frontend Dockerfile
FROM node:18-alpine as build
WORKDIR /app
COPY ./src ./src
COPY ./public ./public
COPY package*.json ./
COPY .eslintrc.js ./
COPY vue.config.js ./
COPY babel.config.js ./
COPY env-frontend .env
RUN CYPRESS_INSTALL_BINARY=0 npm install --no-audit --legacy-peer-deps --loglevel=info && npm run build:prod

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 