from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from .views.auth_views import get_translations, GoogleOAuthView, get_google_oauth_config, AppleOAuthView, register_user, login_user, logout_view, check_auth_status, get_csrf_token, test_csrf, test_redirect_response
from .views.study_views import StudyViewSet, StudyTaskViewSet, MemberViewSet, download_study_excel, upload_study_excel, create_join_request, get_study_join_requests, respond_to_join_request, cancel_join_request, get_user_join_requests, delete_user_study_join_request, translate_text, update_user_language
from .views.question_views import upload_questions, get_questions, get_question_statistics_by_title, bulk_update_question_group, get_ignored_questions, get_question, delete_question, get_question_original_exams, ignore_question, unignore_question, check_question_ignored, update_question, check_existing_file, text_to_questions
from .views.study_progress_views import record_study_progress, get_study_progress_history, get_study_time_statistics
from .views.user_data_views import export_user_data, list_question_files, download_question_file, delete_question_file, update_question_file, user_profile, change_language, UserCreateView, UserUpdateView, download_users_excel, upload_users_excel, delete_user, delete_users_bulk, delete_all_users, search_users, admin_change_user_password, fix_member_user_connections, create_random_recommendation_exam, get_random_recommendation_exam_questions, get_random_exam_email_users, get_users, get_user_profile, update_user_profile, send_email_verification_request, verify_email, manual_retention_cleanup, get_user_statistics_summary, reset_user_statistics, backup_user_statistics, delete_my_account, clear_all_cache, clear_study_cache
from .views.exam_views import create_single_question_exam, delete_question_results, delete_question_results_global, create_exam, get_exam, get_exam_questions, delete_exam, update_exam, update_exam_questions_from_excel, import_questions_from_connected_file, continue_exam, retake_exam, retake_wrong_questions, toggle_exam_original, add_question_to_exam, get_question_member_mappings, get_question_statistics, get_exam_list_for_move, move_questions_to_exam, create_question_member_mapping, get_exams, submit_exam, get_exam_results, exam_result_detail, save_random_practice_result, check_answer, download_exams_excel, upload_exams_excel, move_questions, copy_questions, delete_questions, get_or_create_favorite_exam, add_question_to_favorite, get_favorite_exam_questions, remove_question_from_favorite, get_or_create_daily_exam, adjust_question_accuracy, bulk_adjust_user_accuracy, adjust_single_question_accuracy, get_exam_results_summary, toggle_exam_subscription, bulk_toggle_exam_subscriptions, get_user_exam_subscriptions, get_user_my_exams, get_user_subscribed_exams, move_exams_to_subscribed, move_exams_to_my_exams, shuffle_subscribed_exams, get_exam_connected_studies, get_exam_tags, get_voice_interview_results, get_voice_interview_result_detail, share_voice_interview_result, delete_voice_interview_results, translate_exam, share_exam
from .views.realtime_views import create_realtime_session, get_session_info, get_websocket_url, delete_realtime_session, handle_realtime_function_call, handle_webrtc_offer, handle_ice_candidate, request_speech, stop_speech, get_mandatory_rules_api, get_interview_prompt_template_api, chat_interview
from .views.answer_evaluation_views import evaluate_answer
from .views.health_views import health_check
from .views.short_url_views import create_short_url_api, get_short_url_info, get_user_short_urls, delete_short_url, redirect_short_url
from .views.leetcode_parser_views import parse_leetcode_problems, generate_questions_from_leetcode
from . import views

router = DefaultRouter()
router.register(r'studies', StudyViewSet, basename='study')
router.register(r'study-tasks', StudyTaskViewSet, basename='studytask')
router.register(r'members', MemberViewSet, basename='member')

urlpatterns = [
    path('health/', health_check, name='health_check'),
    path('studies/<int:pk>/members/', StudyViewSet.as_view({'get': 'get_members'}), name='study-members'),
    path('upload-questions/', upload_questions, name='upload_questions'),
    path('text-to-questions/', text_to_questions, name='text_to_questions'),
    path('questions/', get_questions, name='get_questions'),
    path('questions/statistics-by-title/<str:title>/', get_question_statistics_by_title, name='get_question_statistics_by_title'),
    path('questions/bulk-update-group/', bulk_update_question_group, name='bulk_update_question_group'),
    path('questions/ignored/', get_ignored_questions, name='get_ignored_questions'),
    path('questions/<str:question_id>/', get_question, name='get_question'),
    path('questions/<str:question_id>/update/', update_question, name='update_question'),
    path('questions/<str:question_id>/delete/', delete_question, name='delete_question'),
    path('questions/<str:question_id>/original-exams/', get_question_original_exams, name='get_question_original_exams'),
    path('record-study-progress/', record_study_progress, name='record_study_progress'),
    path('study-progress-history/<int:study_id>/', get_study_progress_history, name='get_study_progress_history'),
    path('export-user-data/', export_user_data, name='export_user_data'),
    path('study-time-statistics/<int:study_id>/', get_study_time_statistics, name='get_study_time_statistics'),
    path('create-single-question-exam/', create_single_question_exam, name='create_single_question_exam'),
    path('delete-question-results/', delete_question_results, name='delete_question_results'),
    path('delete-question-results-global/', delete_question_results_global, name='delete_question_results_global'),
    path('create-exam/', create_exam, name='create_exam'),
    path('exam/<uuid:exam_id>/', get_exam, name='get_exam'),
    path('exam/<uuid:exam_id>/questions/', get_exam_questions, name='get_exam_questions'),
    path('exam/<uuid:exam_id>/translate/', translate_exam, name='translate_exam'),
    path('exam/<uuid:exam_id>/delete/', delete_exam, name='delete_exam'),
    path('exam/<uuid:exam_id>/update/', update_exam, name='update_exam'),
    path('exam/<uuid:exam_id>/update-questions-from-excel/', update_exam_questions_from_excel, name='update_exam_questions_from_excel'),
    path('exam/<uuid:exam_id>/import-from-connected-file/', import_questions_from_connected_file, name='import_questions_from_connected_file'),
    path('exam/<uuid:exam_id>/continue/', continue_exam, name='continue_exam'),
    path('exam/<uuid:exam_id>/retake/', retake_exam, name='retake_exam'),
    path('exam/<uuid:exam_id>/wrong-questions/', retake_wrong_questions, name='create_wrong_questions_exam'),
    path('question/<str:question_id>/ignore/', ignore_question, name='ignore_question'),
    path('question/<str:question_id>/unignore/', unignore_question, name='unignore_question'),
    path('question/<str:question_id>/check-ignored/', check_question_ignored, name='check_question_ignored'),
    path('exam/<uuid:exam_id>/toggle-original/', toggle_exam_original, name='toggle_exam_original'),
    path('exam/<uuid:exam_id>/add-question/', add_question_to_exam, name='add_question_to_exam'),
    path('exam/<uuid:exam_id>/question-member-mappings/', get_question_member_mappings, name='get_question_member_mappings'),
    path('exam/<uuid:exam_id>/question-statistics/', get_question_statistics, name='get_question_statistics'),
    path('exam/<uuid:exam_id>/connected-studies/', get_exam_connected_studies, name='get_exam_connected_studies'),
    path('adjust-question-accuracy/', adjust_question_accuracy, name='adjust_question_accuracy'),
    path('bulk-adjust-user-accuracy/', bulk_adjust_user_accuracy, name='bulk_adjust_user_accuracy'),
    path('adjust-single-question-accuracy/', adjust_single_question_accuracy, name='adjust_single_question_accuracy'),
    path('exam-list-for-move/', get_exam_list_for_move, name='get_exam_list_for_move'),
    path('move-questions-to-exam/', move_questions_to_exam, name='move_questions_to_exam'),
    path('create-question-member-mapping/', create_question_member_mapping, name='create_question_member_mapping'),
    path('exams/', get_exams, name='get_exams'),
    path('exams/tags/', get_exam_tags, name='get_exam_tags'),
    path('tags/', include('quiz.views.tag_views')),
    path('tag-categories/', include('quiz.views.tag_category_views')),
    path('submit-exam/', submit_exam, name='submit_exam'),
    path('exam-results/', get_exam_results, name='get_exam_results'),
    path('exam-results/summary/', get_exam_results_summary, name='get_exam_results_summary'),
    path('exam-result/<uuid:result_id>/', exam_result_detail, name='exam_result_detail'),
    path('exam/<uuid:exam_id>/voice-interview-results/', get_voice_interview_results, name='get_voice_interview_results'),
    path('voice-interview-result/<uuid:result_id>/', get_voice_interview_result_detail, name='get_voice_interview_result_detail'),
    path('voice-interview-result/share/', share_voice_interview_result, name='share_voice_interview_result'),
    path('exam/share/', share_exam, name='share_exam'),
    path('voice-interview-results/delete/', delete_voice_interview_results, name='delete_voice_interview_results'),
    path('question-files/', list_question_files, name='list_question_files'),
    path('question-files/check-existing/<str:filename>/', check_existing_file, name='check_existing_file'),
    path('question-files/<str:filename>/download/', download_question_file, name='download_question_file'),
    path('question-files/<str:filename>/delete/', delete_question_file, name='delete_question_file'),
    path('question-files/<str:filename>/', update_question_file, name='update_question_file'),
    path('save-random-practice-result/', save_random_practice_result, name='save_random_practice_result'),
    path('check-answer/', check_answer, name='check_answer'),
    path('user-profile/', user_profile, name='user_profile'),
    path('user-profile/get/', get_user_profile, name='get_user_profile'),
    path('user-profile/update/', update_user_profile, name='update_user_profile'),
    path('send-email-verification/', send_email_verification_request, name='send_email_verification'),
    path('verify-email/<str:token>/', verify_email, name='verify_email'),
    path('change-language/', change_language, name='change_language'),
    path('translations/', get_translations, name='get_translations'),
    path('register/', register_user, name='register'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('login/', login_user, name='login'),
    path('logout/', logout_view, name='logout'),
    path('csrf-token/', get_csrf_token, name='get_csrf_token'),
    path('test-csrf/', test_csrf, name='test_csrf'),
    path('users/', get_users, name='get_users'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/<int:user_id>/', UserUpdateView.as_view(), name='user_update'),
    path('users/download-excel/', download_users_excel, name='download_users_excel'),
    path('users/upload-excel/', upload_users_excel, name='upload_users_excel'),
    path('users/<int:user_id>/delete/', delete_user, name='delete_user'),
    path('users/delete-bulk/', delete_users_bulk, name='delete_users_bulk'),
    path('users/delete-all/', delete_all_users, name='delete_all_users'),
    path('exams/download-excel/', download_exams_excel, name='download_exams_excel'),
    path('exams/upload-excel/', upload_exams_excel, name='upload_exams_excel'),
    path('studies/<int:study_id>/download-excel/', download_study_excel, name='download_study_excel'),
    path('studies/upload-excel/', upload_study_excel, name='upload_study_excel'),
    path('search-users/', search_users, name='search_users'),
    path('google-oauth/', GoogleOAuthView.as_view(), name='google_oauth'),
    path('google-oauth/config/', get_google_oauth_config, name='google_oauth_config'),
    path('apple-oauth/', AppleOAuthView.as_view(), name='apple_oauth'),
    path('test-redirect/', test_redirect_response, name='test_redirect_response'),
    path('auth/status/', check_auth_status, name='check_auth_status'),
    path('favorite-exam/', get_or_create_favorite_exam, name='get_or_create_favorite_exam'),
    path('favorite-exam-questions/', get_favorite_exam_questions, name='get_favorite_exam_questions'),
    path('add-question-to-favorite/', add_question_to_favorite, name='add_question_to_favorite'),
    path('remove-question-from-favorite/', remove_question_from_favorite, name='remove_question_from_favorite'),
    path('user-statistics/summary/', get_user_statistics_summary, name='get_user_statistics_summary'),
    path('user-statistics/reset/', reset_user_statistics, name='reset_user_statistics'),
    path('user-statistics/backup/', backup_user_statistics, name='backup_user_statistics'),
    path('clear-all-cache/', clear_all_cache, name='clear_all_cache'),
    path('', include(router.urls)),
    path('user/<int:user_id>/change-password/', admin_change_user_password, name='admin_change_user_password'),
    path('fix-member-connections/', fix_member_user_connections, name='fix_member_user_connections'),
    path('create-random-recommendation-exam/', create_random_recommendation_exam, name='create_random_recommendation_exam'),
    path('random-recommendation-exam-questions/', get_random_recommendation_exam_questions, name='get_random_recommendation_exam_questions'),
    path('retention-cleanup/manual/', manual_retention_cleanup, name='manual_retention_cleanup'),
    path('random-exam-email-users/', get_random_exam_email_users, name='get_random_exam_email_users'),
    path('daily-exam/', get_or_create_daily_exam, name='get_or_create_daily_exam'),
    # 시험 구독 관련 URL
    path('exam-subscription/toggle/', toggle_exam_subscription, name='toggle_exam_subscription'),
    path('exam-subscription/bulk-toggle/', bulk_toggle_exam_subscriptions, name='bulk_toggle_exam_subscriptions'),
    path('exam-subscription/user/', get_user_exam_subscriptions, name='get_user_exam_subscriptions'),
    # 사용자 시험 관리 관련 URL
    path('user-exams/my-exams/', get_user_my_exams, name='get_user_my_exams'),
    path('user-exams/subscribed-exams/', get_user_subscribed_exams, name='get_user_subscribed_exams'),
    path('user-exams/move-to-subscribed/', move_exams_to_subscribed, name='move_exams_to_subscribed'),
    path('user-exams/move-to-my-exams/', move_exams_to_my_exams, name='move_exams_to_my_exams'),
    path('user-exams/shuffle/', shuffle_subscribed_exams, name='shuffle_subscribed_exams'),
    # 스터디 가입 요청 관련 URL
    path('study-join-request/', create_join_request, name='create_join_request'),
    path('study-join-request/user/', get_user_join_requests, name='get_user_join_requests'),
    path('studies/<int:study_id>/join-requests/', get_study_join_requests, name='get_study_join_requests'),
    path('study-join-request/<int:request_id>/respond/', respond_to_join_request, name='respond_to_join_request'),
    path('study-join-request/<int:request_id>/cancel/', cancel_join_request, name='cancel_join_request'),
    path('study-join-request/user/<int:study_id>/', delete_user_study_join_request, name='delete_user_study_join_request'),
    path('translate/', translate_text, name='translate_text'),
    path('update-user-language/', update_user_language, name='update_user_language'),
    path('delete-my-account/', delete_my_account, name='delete_my_account'),
    # Realtime API 관련 URL
    path('realtime/mandatory-rules/', get_mandatory_rules_api, name='get_mandatory_rules'),
    path('realtime/interview-prompt-template/', get_interview_prompt_template_api, name='get_interview_prompt_template'),
    path('realtime/session/', create_realtime_session, name='create_realtime_session'),
    path('realtime/session/<str:session_id>/', get_session_info, name='get_session_info'),
    path('realtime/session/<str:session_id>/websocket-url/', get_websocket_url, name='get_websocket_url'),
    path('realtime/session/<str:session_id>/delete/', delete_realtime_session, name='delete_realtime_session'),
    path('realtime/function-call/', handle_realtime_function_call, name='handle_realtime_function_call'),
    # WebRTC 관련 URL
    path('realtime/session/<str:session_id>/offer/', handle_webrtc_offer, name='handle_webrtc_offer'),
    path('realtime/session/<str:session_id>/ice-candidate/', handle_ice_candidate, name='handle_ice_candidate'),
    path('realtime/session/<str:session_id>/speak/', request_speech, name='request_speech'),
    path('realtime/session/<str:session_id>/stop-speak/', stop_speech, name='stop_speech'),
    # Chat Completions API 기반 인터뷰 (TTS/STT 조합)
    path('chat/interview/', chat_interview, name='chat_interview'),
    # 답변 평가 관련 URL
    path('evaluate-answer/', evaluate_answer, name='evaluate_answer'),
    # 단축 URL 관련 URL
    path('short-url/create/', create_short_url_api, name='create_short_url'),
    path('short-url/<str:short_code>/', get_short_url_info, name='get_short_url_info'),
    path('short-url/<str:short_code>/delete/', delete_short_url, name='delete_short_url'),
    path('short-urls/', get_user_short_urls, name='get_user_short_urls'),
    # LeetCode 파싱 관련 URL
    path('leetcode/parse/', parse_leetcode_problems, name='parse_leetcode_problems'),
    path('leetcode/generate-questions/', generate_questions_from_leetcode, name='generate_questions_from_leetcode'),
]

urlpatterns += [
    path('move-questions/', move_questions),
    path('copy-questions/', copy_questions),
    path('delete-questions/', delete_questions),
] 