# Generated by Django 4.2.7 on 2025-07-05 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="시험 제목")),
                ("total_questions", models.IntegerField(verbose_name="총 문제 수")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "시험",
                "verbose_name_plural": "시험들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.IntegerField(verbose_name="점수")),
                ("total_score", models.IntegerField(verbose_name="총점")),
                ("correct_count", models.IntegerField(verbose_name="정답 수")),
                ("wrong_count", models.IntegerField(verbose_name="오답 수")),
                (
                    "completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="완료일"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.exam",
                        verbose_name="시험",
                    ),
                ),
            ],
            options={
                "verbose_name": "시험 결과",
                "verbose_name_plural": "시험 결과들",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="문제 내용")),
                ("answer", models.CharField(max_length=500, verbose_name="정답")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "문제",
                "verbose_name_plural": "문제들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamResultDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answer",
                    models.CharField(max_length=500, verbose_name="사용자 답안"),
                ),
                ("is_correct", models.BooleanField(verbose_name="정답 여부")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.question",
                        verbose_name="문제",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.examresult",
                        verbose_name="시험 결과",
                    ),
                ),
            ],
            options={
                "verbose_name": "시험 결과 상세",
                "verbose_name_plural": "시험 결과 상세들",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="순서")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.exam",
                        verbose_name="시험",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.question",
                        verbose_name="문제",
                    ),
                ),
            ],
            options={
                "verbose_name": "시험 문제",
                "verbose_name_plural": "시험 문제들",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="questions",
            field=models.ManyToManyField(
                through="quiz.ExamQuestion", to="quiz.question", verbose_name="문제들"
            ),
        ),
    ]
