# Generated by Django 4.2.7 on 2025-07-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="elapsed_seconds",
            field=models.IntegerField(default=0, verbose_name="소요 시간(초)"),
        ),
    ]
