# Generated by Django 4.2.7 on 2025-07-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_study_studytask"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_original",
            field=models.BooleanField(default=True, verbose_name="원본 여부"),
        ),
        migrations.AddField(
            model_name="exam",
            name="original_exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="quiz.exam",
                verbose_name="원본 시험",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="version_number",
            field=models.IntegerField(default=0, verbose_name="버전 번호"),
        ),
    ]
