# Generated by Django 4.2.7 on 2025-07-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_exam_is_original_exam_original_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="난위도"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="문제 URL"),
        ),
    ]
