# Generated by Django 4.2.7 on 2025-07-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_question_difficulty_question_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="csv_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CSV 문제 ID"
            ),
        ),
    ]
