# Generated by Django 4.2.7 on 2025-07-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_question_csv_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresultdetail",
            name="elapsed_seconds",
            field=models.IntegerField(default=0, verbose_name="문제별 소요 시간(초)"),
        ),
    ]
