# Generated by Django 4.2.7 on 2025-07-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_examresultdetail_elapsed_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("member_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "affiliation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="quiz.study",
                    ),
                ),
            ],
            options={
                "unique_together": {("study", "email")},
            },
        ),
    ]
