# Generated by Django 4.2.7 on 2025-07-06 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionMemberMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_member_mappings",
                        to="quiz.exam",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_mappings",
                        to="quiz.member",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_mappings",
                        to="quiz.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "문제-멤버 매핑",
                "verbose_name_plural": "문제-멤버 매핑들",
                "unique_together": {("question", "member", "exam")},
            },
        ),
    ]
