# Generated by Django 4.2.7 on 2025-07-07 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0012_examresult_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examresult",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StudyTaskProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.FloatField(default=0, verbose_name="진행율")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="업데이트 일시"),
                ),
                (
                    "study_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.studytask",
                        verbose_name="스터디 Task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "스터디 Task 진행율",
                "verbose_name_plural": "스터디 Task 진행율들",
                "unique_together": {("user", "study_task")},
            },
        ),
    ]
