# Generated by Django 4.2.7 on 2025-07-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0013_alter_examresult_user_studytaskprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="file_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="연결된 파일"
            ),
        ),
    ]
