# Generated by Django 4.2.7 on 2025-07-08 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0014_exam_file_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("study", "email")},
        ),
        migrations.AddField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="가입된 사용자",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("study", "email"), ("study", "user")},
        ),
    ]
