# Generated by Django 4.2.7 on 2025-07-08 04:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0015_alter_member_unique_together_member_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("study", "user")},
        ),
    ]
