# Generated by Django 4.2.7 on 2025-07-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0016_alter_member_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True, null=True, verbose_name="설명"),
        ),
    ]
