# Generated by Django 4.2.7 on 2025-07-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0017_question_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="group_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="그룹 ID"
            ),
        ),
    ]
