# Generated by Django 4.2.7 on 2025-07-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0018_question_group_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin_role", "관리자"),
                    ("study_admin_role", "스터디 관리자"),
                    ("user_role", "일반 사용자"),
                ],
                default="user_role",
                max_length=20,
                verbose_name="역할",
            ),
        ),
    ]
