# Generated by Django 4.2.7 on 2025-07-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0019_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "멤버"),
                    ("study_admin", "스터디 관리자"),
                    ("study_leader", "스터디 리더"),
                ],
                default="member",
                max_length=20,
                verbose_name="스터디 내 역할",
            ),
        ),
    ]
