# Generated by Django 4.2.7 on 2025-07-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0020_member_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성화 상태"),
        ),
    ]
