# Generated by Django 4.2.7 on 2025-07-12 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0021_member_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyProgressRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_progress",
                    models.FloatField(default=0, verbose_name="전체 진행율"),
                ),
                (
                    "task_progresses",
                    models.JSONField(default=dict, verbose_name="Task별 진행율"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="기록 일시"),
                ),
                (
                    "page_type",
                    models.CharField(max_length=50, verbose_name="페이지 타입"),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.study",
                        verbose_name="스터디",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "스터디 진행율 기록",
                "verbose_name_plural": "스터디 진행율 기록들",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
