# Generated by Django 4.2.7 on 2025-07-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0022_studyprogressrecord"),
    ]

    operations = []
