# Generated by Django 4.2.7 on 2025-07-13 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0023_auto_20250713_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="공개 여부"),
        ),
    ]
