# Generated by Django 4.2.7 on 2025-07-13 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0024_study_created_by_study_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="생성자",
            ),
        ),
    ]
