# Generated by Django 4.2.7 on 2025-07-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0025_add_created_by_to_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="공개 여부"),
        ),
    ]
