# Generated by Django 4.2.7 on 2025-07-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0026_exam_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ignored_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="무시한 일시"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="무시 이유"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.question",
                        verbose_name="문제",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "무시된 문제",
                "verbose_name_plural": "무시된 문제들",
                "ordering": ["-ignored_at"],
                "unique_together": {("user", "question")},
            },
        ),
    ]
