# Generated by Django 4.2.7 on 2025-07-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0027_ignoredquestion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ignoredquestion",
            name="reason",
        ),
    ]
