# Generated by Django 4.2.7 on 2025-07-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0028_remove_ignoredquestion_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="random_exam_email_enabled",
            field=models.BooleanField(
                default=False, verbose_name="랜덤출제 이메일 발송 여부"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="random_exam_question_count",
            field=models.IntegerField(
                default=3, verbose_name="랜덤출제 시험당 문제 수"
            ),
        ),
    ]
