# Generated by Django 4.2.7 on 2025-07-25 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0029_userprofile_random_exam_email_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="생성일"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="is_original",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="원본 여부"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="is_public",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="공개 여부"
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="completed_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="완료일"
            ),
        ),
        migrations.AlterField(
            model_name="examresultdetail",
            name="is_correct",
            field=models.BooleanField(db_index=True, verbose_name="정답 여부"),
        ),
        migrations.AlterField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="활성화 상태"
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="is_public",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="공개 여부"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_public", "-created_at"], name="quiz_exam_is_publ_34ec1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_original", "-created_at"],
                name="quiz_exam_is_orig_3a4cf0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["original_exam", "version_number"],
                name="quiz_exam_origina_495965_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["user", "-completed_at"], name="quiz_examre_user_id_14150d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["exam", "-completed_at"], name="quiz_examre_exam_id_07a5ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["user", "exam"], name="quiz_examre_user_id_eead43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examresultdetail",
            index=models.Index(
                fields=["result", "is_correct"], name="quiz_examre_result__dec99e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examresultdetail",
            index=models.Index(
                fields=["question", "is_correct"], name="quiz_examre_questio_41fbb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["study", "is_active"], name="quiz_member_study_i_bdb128_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["user", "is_active"], name="quiz_member_user_id_6ddce7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["is_public"], name="quiz_study_is_publ_48bd4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studytask",
            index=models.Index(
                fields=["study", "exam"], name="quiz_studyt_study_i_ab6e80_idx"
            ),
        ),
    ]
