# Generated by Django 4.2.7 on 2025-07-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0030_alter_exam_created_at_alter_exam_is_original_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("ko", "한국어"), ("en", "English")],
                default="en",
                max_length=5,
                verbose_name="언어 설정",
            ),
        ),
    ]
