# Generated by Django 4.2.7 on 2025-07-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0031_userprofile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="시험 설명"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("ko", "한국어"), ("en", "English")],
                default="en",
                max_length=5,
                verbose_name="언어 설정",
            ),
        ),
    ]
