# Generated by Django 4.2.7 on 2025-07-29 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0032_exam_description_alter_userprofile_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="요청 메시지"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("approved", "승인됨"),
                            ("rejected", "거절됨"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청일"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="응답일"),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_join_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="응답자",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="quiz.study",
                        verbose_name="스터디",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "스터디 가입 요청",
                "verbose_name_plural": "스터디 가입 요청들",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["study", "status"],
                        name="quiz_studyj_study_i_dc0949_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="quiz_studyj_user_id_259942_idx"
                    ),
                ],
                "unique_together": {("study", "user")},
            },
        ),
    ]
