# Generated by Django 4.2.7 on 2025-07-29 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0033_studyjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="생성자",
            ),
        ),
        migrations.AddField(
            model_name="studytask",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="공개 여부"),
        ),
    ]
