# Generated by Django 4.2.7 on 2025-08-04 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0034_exam_created_by_studytask_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresultdetail",
            name="question_answer",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="문제 정답"
            ),
        ),
        migrations.AddField(
            model_name="examresultdetail",
            name="question_content",
            field=models.TextField(blank=True, null=True, verbose_name="문제 내용"),
        ),
        migrations.AddField(
            model_name="examresultdetail",
            name="question_difficulty",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="문제 난이도"
            ),
        ),
        migrations.AddField(
            model_name="examresultdetail",
            name="question_title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="문제 제목"
            ),
        ),
        migrations.AlterField(
            model_name="examresultdetail",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quiz.question",
                verbose_name="문제",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="난이도"
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="study",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
