# Generated by Django 4.2.7 on 2025-08-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0035_alter_study_dates_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verification_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="이메일 인증 발송일"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verification_token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="이메일 인증 토큰"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="이메일 인증 완료"),
        ),
    ]
