# Generated by Django 4.2.7 on 2025-08-08 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0036_userprofile_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccuracyAdjustmentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "adjustment_count",
                    models.IntegerField(default=1, verbose_name="조정 횟수"),
                ),
                (
                    "total_adjustment_percentage",
                    models.FloatField(default=10.0, verbose_name="총 조정 퍼센트"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.exam",
                        verbose_name="시험",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.question",
                        verbose_name="문제",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "정확도 조정 이력",
                "verbose_name_plural": "정확도 조정 이력들",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "question"],
                        name="quiz_accura_user_id_d30602_idx",
                    ),
                    models.Index(
                        fields=["user", "exam"], name="quiz_accura_user_id_75f1b3_idx"
                    ),
                ],
                "unique_together": {("user", "question", "exam")},
            },
        ),
    ]
