# Generated by Django 4.2.7 on 2025-08-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0037_accuracyadjustmenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="retention_cleanup_enabled",
            field=models.BooleanField(default=False, verbose_name="자동 정리 활성화"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="retention_cleanup_percentage",
            field=models.IntegerField(
                default=0,
                help_text="매일 성공한 기록 중 삭제할 비율 (0-100%)",
                verbose_name="자동 정리 비율",
            ),
        ),
    ]
