# Generated by Django 4.2.7 on 2025-08-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0038_userprofile_retention_cleanup_enabled_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["title"], name="quiz_exam_title_547e9d_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="quiz_exam_created_f89dae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_public", "is_original", "-created_at"],
                name="quiz_exam_is_publ_55f289_idx",
            ),
        ),
    ]
