# Generated by Django 4.2.7 on 2025-08-15 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0039_add_exam_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="구독일"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.exam",
                        verbose_name="시험",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "시험 구독",
                "verbose_name_plural": "시험 구독들",
                "ordering": ["-subscribed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="quiz_examsu_user_id_f4e2a9_idx",
                    ),
                    models.Index(
                        fields=["exam", "is_active"],
                        name="quiz_examsu_exam_id_318b3b_idx",
                    ),
                    models.Index(
                        fields=["user", "exam"], name="quiz_examsu_user_id_bf1d3a_idx"
                    ),
                ],
                "unique_together": {("user", "exam")},
            },
        ),
    ]
