# Generated by Django 4.2.7 on 2025-08-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0040_examsubscription"),
    ]

    operations = [
        # 1. 먼저 Django 모델 상태에 seq 필드 추가
        migrations.AddField(
            model_name="studytask",
            name="seq",
            field=models.IntegerField(default=0, verbose_name="순서"),
        ),
        # 2. 그 다음 인덱스 추가 (이제 seq 필드가 모델 상태에 존재함)
        migrations.AddIndex(
            model_name="studytask",
            index=models.Index(
                fields=["study", "seq"], name="quiz_studyt_study_i_3cb2f1_idx"
            ),
        ),
        # 3. 마지막에 모델 옵션 설정
        migrations.AlterModelOptions(
            name="studytask",
            options={
                "ordering": ["study", "seq"],
                "verbose_name": "학습 태스크",
                "verbose_name_plural": "학습 태스크들",
            },
        ),
    ]
