# Generated by Django 4.2.7 on 2025-08-17 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0041_add_seq_field_to_studytask_clean"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="study",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="생성일",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="study",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["created_at"], name="quiz_study_created_b7ff98_idx"
            ),
        ),
    ]
