# Generated by Django 4.2.7 on 2025-08-18 00:11

from django.db import migrations, models


def migrate_existing_study_data(apps, schema_editor):
    """
    기존 Study 데이터를 다국어 필드로 마이그레이션
    """
    Study = apps.get_model('quiz', 'Study')
    
    for study in Study.objects.all():
        # 한국어 제목을 기본 제목으로 설정
        if study.title_ko:
            study.title = study.title_ko
        
        # 한국어 목표를 기본 목표로 설정
        if study.goal_ko:
            study.goal = study.goal_ko
        
        study.save()


def reverse_migrate(apps, schema_editor):
    """
    마이그레이션 되돌리기 (필요시)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0042_alter_study_options_study_created_at_and_more"),
    ]

    operations = [
        # 1단계: 다국어 필드 추가 (데이터 마이그레이션 전에 필드가 존재해야 함)
        migrations.AddField(
            model_name="study",
            name="created_language",
            field=models.CharField(
                choices=[("ko", "한국어"), ("en", "English")],
                default="ko",
                max_length=2,
                verbose_name="생성 언어",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="goal_en",
            field=models.TextField(blank=True, verbose_name="영어 목표"),
        ),
        migrations.AddField(
            model_name="study",
            name="goal_ko",
            field=models.TextField(blank=True, verbose_name="한국어 목표"),
        ),
        migrations.AddField(
            model_name="study",
            name="is_en_complete",
            field=models.BooleanField(default=False, verbose_name="영어 완성"),
        ),
        migrations.AddField(
            model_name="study",
            name="is_ko_complete",
            field=models.BooleanField(default=False, verbose_name="한국어 완성"),
        ),
        migrations.AddField(
            model_name="study",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="영어 제목"
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="title_ko",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="한국어 제목"
            ),
        ),
        
        # 2단계: 데이터 마이그레이션 실행 (이제 다국어 필드가 존재함)
        migrations.RunPython(migrate_existing_study_data, reverse_migrate),
        
        # 3단계: 기존 필드 제거하지 않음 (title과 goal 필드 유지)
        # migrations.RemoveField(
        #     model_name="study",
        #     name="goal",
        # ),
        # migrations.RemoveField(
        #     model_name="study",
        #     name="title",
        # ),
        
        # 4단계: 인덱스 추가
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["created_language"], name="quiz_study_created_8b83b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["is_ko_complete"], name="quiz_study_is_ko_c_fa2f94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["is_en_complete"], name="quiz_study_is_en_c_435be6_idx"
            ),
        ),
    ]
