# Generated by Django 4.2.7 on 2025-08-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0043_remove_study_goal_remove_study_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studytask",
            name="created_language",
            field=models.CharField(
                choices=[("ko", "한국어"), ("en", "English")],
                default="ko",
                max_length=2,
                verbose_name="생성 언어",
            ),
        ),
        migrations.AddField(
            model_name="studytask",
            name="is_en_complete",
            field=models.BooleanField(default=False, verbose_name="영어 완성"),
        ),
        migrations.AddField(
            model_name="studytask",
            name="is_ko_complete",
            field=models.BooleanField(default=False, verbose_name="한국어 완성"),
        ),
        migrations.AddField(
            model_name="studytask",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="영어 Task 이름"
            ),
        ),
        migrations.AddField(
            model_name="studytask",
            name="name_ko",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="한국어 Task 이름"
            ),
        ),
        migrations.AlterField(
            model_name="studytask",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="studytask",
            index=models.Index(
                fields=["created_language"], name="quiz_studyt_created_ded9a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studytask",
            index=models.Index(
                fields=["is_ko_complete"], name="quiz_studyt_is_ko_c_cbaf72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studytask",
            index=models.Index(
                fields=["is_en_complete"], name="quiz_studyt_is_en_c_1ae4ad_idx"
            ),
        ),
    ]
