# Generated by Django 4.2.7 on 2025-08-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0045_add_multilingual_to_studytask"),
    ]

    operations = [
        # 기존 title 인덱스 제거 (필드 자체는 유지)
        migrations.RemoveIndex(
            model_name="exam",
            name="quiz_exam_title_547e9d_idx",
        ),
        
        # 기존 필드 제거하지 않음 (title과 description 필드 유지)
        # migrations.RemoveField(
        #     model_name="exam",
        #     name="description",
        # ),
        # migrations.RemoveField(
        #     model_name="exam",
        #     name="title",
        # ),
        
        # 다국어 필드 추가
        migrations.AddField(
            model_name="exam",
            name="created_language",
            field=models.CharField(
                choices=[("ko", "한국어"), ("en", "English")],
                default="ko",
                max_length=2,
                verbose_name="생성 언어",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="영어 설명"),
        ),
        migrations.AddField(
            model_name="exam",
            name="description_ko",
            field=models.TextField(blank=True, null=True, verbose_name="한국어 설명"),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_en_complete",
            field=models.BooleanField(default=False, verbose_name="영어 완성"),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_ko_complete",
            field=models.BooleanField(default=False, verbose_name="한국어 완성"),
        ),
        migrations.AddField(
            model_name="exam",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="영어 제목"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="title_ko",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="한국어 제목"
            ),
        ),
        
        # 다국어 필드 인덱스 추가
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["title_ko"], name="quiz_exam_title_k_7c8ce2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["title_en"], name="quiz_exam_title_e_bda3d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["created_language"], name="quiz_exam_created_226b5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_ko_complete"], name="quiz_exam_is_ko_c_604553_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_en_complete"], name="quiz_exam_is_en_c_ada82b_idx"
            ),
        ),
    ]
