# Generated by Django 4.2.7 on 2025-08-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0046_add_multilingual_to_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_en",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="영어 정답"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_ko",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="한국어 정답"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="content_en",
            field=models.TextField(blank=True, verbose_name="영어 문제 내용"),
        ),
        migrations.AddField(
            model_name="question",
            name="content_ko",
            field=models.TextField(blank=True, verbose_name="한국어 문제 내용"),
        ),
        migrations.AddField(
            model_name="question",
            name="created_language",
            field=models.CharField(
                choices=[("ko", "한국어"), ("en", "English")],
                default="ko",
                max_length=2,
                verbose_name="생성 언어",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_en",
            field=models.TextField(blank=True, null=True, verbose_name="영어 설명"),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_ko",
            field=models.TextField(blank=True, null=True, verbose_name="한국어 설명"),
        ),
        migrations.AddField(
            model_name="question",
            name="is_en_complete",
            field=models.BooleanField(default=False, verbose_name="영어 완성"),
        ),
        migrations.AddField(
            model_name="question",
            name="is_ko_complete",
            field=models.BooleanField(default=False, verbose_name="한국어 완성"),
        ),
        migrations.AddField(
            model_name="question",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="영어 제목"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="title_ko",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="한국어 제목"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["title_ko"], name="quiz_questi_title_k_b8de71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["title_en"], name="quiz_questi_title_e_1dc65d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["content_ko"], name="quiz_questi_content_cf72b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["content_en"], name="quiz_questi_content_a3cafe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["created_language"], name="quiz_questi_created_0d3e32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_ko_complete"], name="quiz_questi_is_ko_c_50306a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_en_complete"], name="quiz_questi_is_en_c_3b7389_idx"
            ),
        ),
    ]
