# Generated by Django 4.2.7 on 2025-08-18 22:45
# 
# 🚨 중요: 이 마이그레이션은 기존 데이터를 다국어 필드로 복사합니다!
# 
# 마이그레이션 전략:
# 1. 모든 모델에 다국어 필드 추가
# 2. 기존 데이터를 다국어 필드로 복사
# 3. 기존 필드는 유지 (나중에 별도 마이그레이션으로 제거)
#
# 적용 대상:
# - Study: title, goal → title_ko, title_en, goal_ko, goal_en
# - Exam: title, description → title_ko, title_en, description_ko, description_en
# - Question: title, content, answer, explanation → title_ko, title_en, content_ko, content_en, answer_ko, answer_en, explanation_ko, explanation_en

from django.db import migrations, models

def migrate_study_data(apps, schema_editor):
    """Study 모델의 기존 데이터를 다국어 필드로 마이그레이션"""
    Study = apps.get_model('quiz', 'Study')

    from django.db import connection
    
    with connection.cursor() as cursor:
        # 기존 title과 goal 값 조회
        cursor.execute("""
            SELECT id, title, goal 
            FROM quiz_study 
            WHERE title IS NOT NULL OR goal IS NOT NULL
        """)
        
        for row in cursor.fetchall():
            study_id, title, goal = row
            study = Study.objects.get(id=study_id)
            
            # 기존 title을 한국어로 설정
            if title:
                study.title_ko = title
                study.title_en = title  # 임시로 영어 필드에도 동일한 값 설정
                study.is_ko_complete = True
                study.is_en_complete = False
            
            # 기존 goal을 한국어로 설정
            if goal:
                study.goal_ko = goal
                study.goal_en = ""  # 영어 목표는 빈 값으로 유지
                study.is_ko_complete = study.is_ko_complete and True
                study.is_en_complete = study.is_en_complete and False
            
            # 생성 언어를 한국어로 설정
            study.created_language = 'ko'
            
            study.save()

def migrate_exam_data(apps, schema_editor):
    """Exam 모델의 기존 데이터를 다국어 필드로 마이그레이션"""
    Exam = apps.get_model('quiz', 'Exam')

    from django.db import connection
    
    with connection.cursor() as cursor:
        # 기존 title과 description 값 조회
        cursor.execute("""
            SELECT id, title, description 
            FROM quiz_exam 
            WHERE title IS NOT NULL OR description IS NOT NULL
        """)
        
        for row in cursor.fetchall():
            exam_id, title, description = row
            exam = Exam.objects.get(id=exam_id)
            
            # 기존 title을 한국어로 설정
            if title:
                exam.title_ko = title
                exam.title_en = title  # 임시로 영어 필드에도 동일한 값 설정
                exam.is_ko_complete = True
                exam.is_en_complete = False
            
            # 기존 description을 한국어로 설정
            if description:
                exam.description_ko = description
                exam.description_en = ""  # 영어 설명은 빈 값으로 유지
                exam.is_ko_complete = exam.is_ko_complete and True
                exam.is_en_complete = exam.is_en_complete and False
            
            # 생성 언어를 한국어로 설정
            exam.created_language = 'ko'
            
            exam.save()

def migrate_question_data(apps, schema_editor):
    """Question 모델의 기존 데이터를 다국어 필드로 마이그레이션"""
    Question = apps.get_model('quiz', 'Question')

    from django.db import connection
    
    with connection.cursor() as cursor:
        # 기존 title, content, answer, explanation 값 조회
        cursor.execute("""
            SELECT id, title, content, answer, explanation 
            FROM quiz_question 
            WHERE title IS NOT NULL OR content IS NOT NULL OR answer IS NOT NULL OR explanation IS NOT NULL
        """)
        
        for row in cursor.fetchall():
            question_id, title, content, answer, explanation = row
            question = Question.objects.get(id=question_id)
            
            # 기존 title을 한국어로 설정
            if title:
                question.title_ko = title
                question.title_en = title  # 임시로 영어 필드에도 동일한 값 설정
                question.is_ko_complete = True
                question.is_en_complete = False
            
            # 기존 content를 한국어로 설정
            if content:
                question.content_ko = content
                question.content_en = content  # 임시로 영어 필드에도 동일한 값 설정
                question.is_ko_complete = question.is_ko_complete and True
                question.is_en_complete = question.is_en_complete and False
            
            # 기존 answer를 한국어로 설정
            if answer:
                question.answer_ko = answer
                question.answer_en = answer  # 임시로 영어 필드에도 동일한 값 설정
                question.is_ko_complete = question.is_ko_complete and True
                question.is_en_complete = question.is_en_complete and False
            
            # 기존 explanation을 한국어로 설정
            if explanation:
                question.explanation_ko = explanation
                question.explanation_en = ""  # 영어 설명은 빈 값으로 유지
                question.is_ko_complete = question.is_ko_complete and True
                question.is_en_complete = question.is_en_complete and False
            
            # 생성 언어를 한국어로 설정
            question.created_language = 'ko'
            
            question.save()

def reverse_migrate(apps, schema_editor):
    """마이그레이션 되돌리기 (필요시)"""
    # 역방향 마이그레이션은 복잡하므로 필요시 별도 구현
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0048_add_created_by_to_question"),
    ]

    operations = [
        # ⚠️ 주의: 모든 AddField 작업이 제거됨
        # 다국어 필드들(created_language, goal_en, goal_ko, title_en, title_ko, is_en_complete, is_ko_complete)
        # 은 이미 모델에 정의되어 있고 다른 마이그레이션(0046, 0047, 0050)에서 처리됨

        # 4단계: 데이터 마이그레이션 실행만 수행
        migrations.RunPython(migrate_study_data, reverse_migrate),
        migrations.RunPython(migrate_exam_data, reverse_migrate),
        migrations.RunPython(migrate_question_data, reverse_migrate),
    ]
