# Generated by Django 4.2.7 on 2025-08-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0049_comprehensive_multilingual_migration"),
        ("quiz", "0050_safe_multilingual_migration"),
    ]

    operations = []
