# Generated by Django 4.2.7 on 2025-08-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0051_merge_20250818_1547"),
    ]

    operations = [
        # ⚠️ Note: The following indexes were never created due to migration changes,
        # so RemoveIndex operations have been removed to prevent errors
        # migrations.RemoveIndex(model_name="exam", name="quiz_exam_created_lang_idx"),
        # migrations.RemoveIndex(model_name="exam", name="quiz_exam_is_ko_complete_idx"),
        # migrations.RemoveIndex(model_name="exam", name="quiz_exam_is_en_complete_idx"),
        # migrations.RemoveIndex(model_name="question", name="quiz_question_created_lang_idx"),
        # migrations.RemoveIndex(model_name="question", name="quiz_question_is_ko_complete_idx"),
        # migrations.RemoveIndex(model_name="question", name="quiz_question_is_en_complete_idx"),
        # migrations.RemoveIndex(model_name="study", name="quiz_study_created_lang_idx"),
        # migrations.RemoveIndex(model_name="study", name="quiz_study_is_ko_complete_idx"),
        # migrations.RemoveIndex(model_name="study", name="quiz_study_is_en_complete_idx"),

        migrations.RemoveField(
            model_name="exam",
            name="description",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="title",
        ),
        migrations.RemoveField(
            model_name="study",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="study",
            name="title",
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty"], name="quiz_questi_difficu_fde0f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["group_id"], name="quiz_questi_group_i_97770e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["csv_id"], name="quiz_questi_csv_id_404742_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["created_at"], name="quiz_questi_created_4bf6e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["updated_at"], name="quiz_questi_updated_141404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["created_language", "is_ko_complete"],
                name="quiz_questi_created_da0b90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["created_language", "is_en_complete"],
                name="quiz_questi_created_222c73_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty", "created_language"],
                name="quiz_questi_difficu_1886bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["group_id", "created_language"],
                name="quiz_questi_group_i_fc1ccc_idx",
            ),
        ),
    ]
