# Generated by Django 4.2.7 on 2025-08-22 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0053_fix_cascade_to_set_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accuracyadjustmenthistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="생성자",
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="examsubscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="ignoredquestion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="studyjoinrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="요청자",
            ),
        ),
        migrations.AlterField(
            model_name="studyprogressrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="studytaskprogress",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.CreateModel(
            name="QuestionFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="파일명"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="파일 경로"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="파일 크기")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="공개 여부"),
                ),
                (
                    "max_questions",
                    models.IntegerField(default=0, verbose_name="최대 문제 수"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로드자",
                    ),
                ),
            ],
            options={
                "verbose_name": "문제 파일",
                "verbose_name_plural": "문제 파일들",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["file_name"], name="quiz_questi_file_na_872b23_idx"
                    ),
                    models.Index(
                        fields=["is_public"], name="quiz_questi_is_publ_a4bbad_idx"
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="quiz_questi_uploade_2eb566_idx"
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="quiz_questi_uploade_7c2c60_idx"
                    ),
                ],
            },
        ),
    ]
