# Generated by Django 4.2.7 on 2025-08-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0054_alter_accuracyadjustmenthistory_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuestionFile",
        ),
    ]
