# Generated by Django 4.2.7 on 2025-08-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0055_delete_questionfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="force_answer",
            field=models.BooleanField(
                default=False,
                help_text="체크하면 Pass/Fail 버튼 대신 Submit 버튼으로 답안을 검증합니다",
                verbose_name="답안 입력 강제",
            ),
        ),
    ]
