# Generated by Django 4.2.7 on 2025-08-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0056_add_force_answer_to_exam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="title",
        ),
    ]
