# Generated by Django 4.2.7 on 2025-08-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0057_remove_title_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studytask",
            name="name",
        ),
    ]
