# Generated by Django 4.2.7 on 2025-08-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0058_remove_studytask_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation",
        ),
    ]
