# Generated by Django 4.2.7 on 2025-08-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0059_remove_legacy_content_answer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_id',
            field=models.CharField(
                blank=True, 
                max_length=200, 
                null=True, 
                verbose_name='출처 파일명',
                help_text='엑셀 파일명 또는 문제 출처를 나타내는 식별자'
            ),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['source_id'], name='quiz_quest_source_id_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['source_id', 'title_ko'], name='quiz_quest_source_title_ko_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['source_id', 'title_en'], name='quiz_quest_source_title_en_idx'),
        ),
    ]
