# Generated by Django 4.2.7 on 2025-08-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0060_add_source_id_to_question"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="question",
            new_name="quiz_questi_source__82533f_idx",
            old_name="quiz_quest_source_id_idx",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="quiz_questi_source__58d469_idx",
            old_name="quiz_quest_source_title_ko_idx",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="quiz_questi_source__cba123_idx",
            old_name="quiz_quest_source_title_en_idx",
        ),
    ]
