# Generated by Django 4.2.7 on 2025-09-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0061_rename_quiz_quest_source_id_idx_quiz_questi_source__82533f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='voice_mode_enabled',
            field=models.BooleanField(default=False, help_text='체크하면 음성으로 시험을 볼 수 있습니다', verbose_name='음성 모드 지원'),
        ),
    ]
