# Generated by Django 4.2.7 on 2025-09-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0062_add_voice_mode_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ai_mock_interview',
            field=models.BooleanField(default=False, help_text='체크하면 AI와 함께 모의 인터뷰를 진행할 수 있습니다', verbose_name='AI 모의 인터뷰'),
        ),
    ]
