# Generated by Django 4.2.7 on 2025-09-21 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0063_add_ai_mock_interview_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="영어 설명"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="description_ko",
            field=models.TextField(blank=True, null=True, verbose_name="한국어 설명"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_en",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="영어 정답"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_ko",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="한국어 정답"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="content_en",
            field=models.TextField(blank=True, verbose_name="영어 문제 내용"),
        ),
        migrations.AlterField(
            model_name="question",
            name="content_ko",
            field=models.TextField(blank=True, verbose_name="한국어 문제 내용"),
        ),
        migrations.AlterField(
            model_name="question",
            name="explanation_en",
            field=models.TextField(blank=True, null=True, verbose_name="영어 설명"),
        ),
        migrations.AlterField(
            model_name="question",
            name="explanation_ko",
            field=models.TextField(blank=True, null=True, verbose_name="한국어 설명"),
        ),
        migrations.CreateModel(
            name="ShortUrl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        db_index=True,
                        max_length=10,
                        unique=True,
                        verbose_name="단축 코드",
                    ),
                ),
                (
                    "original_url",
                    models.URLField(max_length=2000, verbose_name="원본 URL"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="만료일이 설정되면 해당 시간 이후 URL이 무효화됩니다",
                        null=True,
                        verbose_name="만료일",
                    ),
                ),
                (
                    "access_count",
                    models.IntegerField(default=0, verbose_name="접근 횟수"),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 접근일"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "단축 URL",
                "verbose_name_plural": "단축 URL들",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["short_code"], name="quiz_shortu_short_c_d05d76_idx"
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="quiz_shortu_created_e11c18_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="quiz_shortu_expires_ae9a72_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="quiz_shortu_created_25288b_idx"
                    ),
                ],
            },
        ),
    ]
