# Generated by Django 4.2.7 on 2025-09-21 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0065_alter_exam_description_en_alter_exam_description_ko_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ko",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="한국어 태그명"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="영어 태그명"
                    ),
                ),
                (
                    "is_ko_complete",
                    models.BooleanField(default=False, verbose_name="한국어 완성"),
                ),
                (
                    "is_en_complete",
                    models.BooleanField(default=False, verbose_name="영어 완성"),
                ),
                (
                    "created_language",
                    models.CharField(
                        choices=[("ko", "한국어"), ("en", "English")],
                        default="ko",
                        max_length=2,
                        verbose_name="생성 언어",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "태그",
                "verbose_name_plural": "태그들",
                "ordering": ["name_ko"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="exams", to="quiz.tag", verbose_name="태그들"
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="studies", to="quiz.tag", verbose_name="태그들"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name_ko"], name="quiz_tag_name_ko_ebad0a_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name_en"], name="quiz_tag_name_en_0c2e19_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["created_language"], name="quiz_tag_created_9deafa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["is_ko_complete"], name="quiz_tag_is_ko_c_899d63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["is_en_complete"], name="quiz_tag_is_en_c_b52cd5_idx"
            ),
        ),
    ]
