# Generated by Django 4.2.7 on 2025-09-22 05:10

from django.db import migrations


def update_user_language_default(apps, schema_editor):
    """기존 사용자들의 언어 설정을 영어로 업데이트"""
    UserProfile = apps.get_model('quiz', 'UserProfile')
    
    # language가 None이거나 빈 값인 사용자들을 영어로 설정
    UserProfile.objects.filter(
        language__isnull=True
    ).update(language='en')
    
    UserProfile.objects.filter(
        language=''
    ).update(language='en')


def reverse_update_user_language_default(apps, schema_editor):
    """마이그레이션 되돌리기 (기본값을 한국어로 복원)"""
    UserProfile = apps.get_model('quiz', 'UserProfile')
    
    # 영어로 설정된 사용자들을 한국어로 변경
    UserProfile.objects.filter(language='en').update(language='ko')


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0066_tag_exam_tags_study_tags_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_user_language_default,
            reverse_update_user_language_default
        ),
    ]
