# Generated by Django 4.2.7 on 2025-10-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0067_update_user_language_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_en",
            field=models.TextField(blank=True, verbose_name="영어 정답"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_ko",
            field=models.TextField(blank=True, verbose_name="한국어 정답"),
        ),
    ]
