# Generated by Django 4.2.7 on 2025-11-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0068_change_answer_fields_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auto_translation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="자동 번역 기능을 사용할지 여부",
                verbose_name="자동 번역 지원 사용",
            ),
        ),
    ]
