# Generated by Django 4.2.7 on 2025-11-18 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0069_userprofile_auto_translation_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ko",
                    models.CharField(max_length=100, verbose_name="한국어 카테고리명"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="영어 카테고리명"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(1, "1단계"), (2, "2단계"), (3, "3단계")],
                        db_index=True,
                        default=1,
                        verbose_name="레벨",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="UI에서 사용할 색상 코드 (예: 🟩, 🟦, 🟨)",
                        max_length=20,
                        null=True,
                        verbose_name="색상 코드",
                    ),
                ),
                (
                    "is_ko_complete",
                    models.BooleanField(default=False, verbose_name="한국어 완성"),
                ),
                (
                    "is_en_complete",
                    models.BooleanField(default=False, verbose_name="영어 완성"),
                ),
                (
                    "created_language",
                    models.CharField(
                        choices=[("ko", "한국어"), ("en", "English")],
                        default="ko",
                        max_length=2,
                        verbose_name="생성 언어",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="quiz.tagcategory",
                        verbose_name="상위 카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "태그 카테고리",
                "verbose_name_plural": "태그 카테고리들",
                "ordering": ["level", "order", "name_ko"],
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="tags",
                to="quiz.tagcategory",
                verbose_name="카테고리들",
            ),
        ),
        migrations.AddIndex(
            model_name="tagcategory",
            index=models.Index(
                fields=["parent", "level"], name="quiz_tagcat_parent__3009fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tagcategory",
            index=models.Index(
                fields=["level", "order"], name="quiz_tagcat_level_db2d2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tagcategory",
            index=models.Index(
                fields=["name_ko"], name="quiz_tagcat_name_ko_1bde3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tagcategory",
            index=models.Index(
                fields=["name_en"], name="quiz_tagcat_name_en_f7cddb_idx"
            ),
        ),
    ]
