# Generated by Django 4.2.7 on 2025-11-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0073_add_is_active_to_tagcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="supported_languages",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text='콤마로 구분된 언어 코드 (예: "ko,en")',
                max_length=20,
                verbose_name="지원 언어",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="supported_languages",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text='콤마로 구분된 언어 코드 (예: "ko,en")',
                max_length=20,
                verbose_name="지원 언어",
            ),
        ),
        migrations.AddField(
            model_name="studytask",
            name="supported_languages",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text='콤마로 구분된 언어 코드 (예: "ko,en")',
                max_length=20,
                verbose_name="지원 언어",
            ),
        ),
    ]
