# Generated by Django 4.2.7 on 2025-11-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0074_exam_supported_languages_study_supported_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interested_categories',
            field=models.ManyToManyField(
                blank=True,
                help_text='사용자가 관심있는 카테고리 목록',
                related_name='interested_users',
                to='quiz.tagcategory',
                verbose_name='관심 카테고리'
            ),
        ),
    ]







