# Generated by Django 4.2.7 on 2025-11-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0075_userprofile_interested_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresultdetail',
            name='question_answer',
            field=models.TextField(blank=True, null=True, verbose_name='문제 정답'),
        ),
        migrations.AlterField(
            model_name='examresultdetail',
            name='user_answer',
            field=models.TextField(verbose_name='사용자 답안'),
        ),
    ]


