# Generated by Django 4.2.7 on 2025-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0076_change_examresultdetail_answer_fields_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="description_es",
            field=models.TextField(blank=True, null=True, verbose_name="스페인어 설명"),
        ),
        migrations.AddField(
            model_name="exam",
            name="description_zh",
            field=models.TextField(blank=True, null=True, verbose_name="중국어 설명"),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_es_complete",
            field=models.BooleanField(default=False, verbose_name="스페인어 완성"),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_zh_complete",
            field=models.BooleanField(default=False, verbose_name="중국어 완성"),
        ),
        migrations.AddField(
            model_name="exam",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="스페인어 제목"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="title_zh",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="중국어 제목"
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="goal_es",
            field=models.TextField(blank=True, verbose_name="스페인어 목표"),
        ),
        migrations.AddField(
            model_name="study",
            name="goal_zh",
            field=models.TextField(blank=True, verbose_name="중국어 목표"),
        ),
        migrations.AddField(
            model_name="study",
            name="is_es_complete",
            field=models.BooleanField(default=False, verbose_name="스페인어 완성"),
        ),
        migrations.AddField(
            model_name="study",
            name="is_zh_complete",
            field=models.BooleanField(default=False, verbose_name="중국어 완성"),
        ),
        migrations.AddField(
            model_name="study",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="스페인어 제목"
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="title_zh",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="중국어 제목"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="created_language",
            field=models.CharField(
                choices=[
                    ("ko", "한국어"),
                    ("en", "English"),
                    ("es", "Español"),
                    ("zh", "中文"),
                ],
                default="ko",
                max_length=2,
                verbose_name="생성 언어",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="created_language",
            field=models.CharField(
                choices=[
                    ("ko", "한국어"),
                    ("en", "English"),
                    ("es", "Español"),
                    ("zh", "中文"),
                ],
                default="ko",
                max_length=2,
                verbose_name="생성 언어",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["title_es"], name="quiz_exam_title_e_e728f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["title_zh"], name="quiz_exam_title_z_74b12e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_es_complete"], name="quiz_exam_is_es_c_9b101c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_zh_complete"], name="quiz_exam_is_zh_c_faf796_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["is_es_complete"], name="quiz_study_is_es_c_3c2707_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["is_zh_complete"], name="quiz_study_is_zh_c_9e458d_idx"
            ),
        ),
    ]
