# Generated by Django 4.2.7 on 2025-11-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0079_add_japanese_support"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="exam",
            name="quiz_exam_is_ja_c_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="exam",
            new_name="quiz_exam_title_j_bf8af9_idx",
            old_name="quiz_exam_title_j_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="quiz_questi_title_j_341924_idx",
            old_name="quiz_questi_title_j_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="quiz_questi_content_9f8b28_idx",
            old_name="quiz_questi_content_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="quiz_questi_is_ja_c_b5d75c_idx",
            old_name="quiz_questi_is_ja_c_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="quiz_questi_created_c7a5f8_idx",
            old_name="quiz_questi_created_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="quiz_questi_source__da3423_idx",
            old_name="quiz_questi_source__abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="study",
            new_name="quiz_study_is_ja_c_496b25_idx",
            old_name="quiz_study_is_ja_c_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="tagcategory",
            new_name="quiz_tagcat_name_es_9c0c6b_idx",
            old_name="quiz_tagcat_name_es_idx",
        ),
        migrations.RenameIndex(
            model_name="tagcategory",
            new_name="quiz_tagcat_name_zh_4d28c6_idx",
            old_name="quiz_tagcat_name_zh_idx",
        ),
        migrations.AddField(
            model_name="tagcategory",
            name="name_ja",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="일본어 카테고리명"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="created_language",
            field=models.CharField(
                choices=[
                    ("ko", "한국어"),
                    ("en", "English"),
                    ("es", "Español"),
                    ("zh", "中文"),
                    ("ja", "日本語"),
                ],
                default="en",
                max_length=2,
                verbose_name="생성 언어",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="created_language",
            field=models.CharField(
                choices=[
                    ("ko", "한국어"),
                    ("en", "English"),
                    ("es", "Español"),
                    ("zh", "中文"),
                    ("ja", "日本語"),
                ],
                default="en",
                max_length=2,
                verbose_name="생성 언어",
            ),
        ),
        migrations.AlterField(
            model_name="studytask",
            name="created_language",
            field=models.CharField(
                choices=[
                    ("ko", "한국어"),
                    ("en", "English"),
                    ("es", "Español"),
                    ("zh", "中文"),
                    ("ja", "日本語"),
                ],
                default="en",
                max_length=2,
                verbose_name="생성 언어",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_language",
            field=models.CharField(
                choices=[
                    ("ko", "한국어"),
                    ("en", "English"),
                    ("es", "Español"),
                    ("zh", "中文"),
                    ("ja", "日本語"),
                ],
                default="en",
                max_length=2,
                verbose_name="생성 언어",
            ),
        ),
        migrations.AddIndex(
            model_name="tagcategory",
            index=models.Index(
                fields=["name_ja"], name="quiz_tagcat_name_ja_adf176_idx"
            ),
        ),
    ]
