# Generated by Django 4.2.7 on 2025-11-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0080_add_name_ja_to_tagcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="is_voice_interview",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Voice Interview 모드로 진행된 시험 결과인지 여부",
                verbose_name="음성 인터뷰 결과",
            ),
        ),
        migrations.AddField(
            model_name="examresultdetail",
            name="evaluation",
            field=models.TextField(
                blank=True,
                help_text="Voice Interview 모드에서 AI가 제공한 평가 내용",
                null=True,
                verbose_name="AI 평가 내용",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[
                    ("ko", "한국어"),
                    ("en", "English"),
                    ("es", "Español"),
                    ("zh", "中文"),
                    ("ja", "日本語"),
                ],
                default="en",
                max_length=5,
                verbose_name="언어 설정",
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["exam", "is_voice_interview", "-completed_at"],
                name="quiz_examre_exam_id_3cbc7c_idx",
            ),
        ),
    ]
