# Generated by Django 4.2.7 on 2025-11-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0081_add_voice_interview_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="is_es_complete",
            field=models.BooleanField(default=False, verbose_name="스페인어 완성"),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_ja_complete",
            field=models.BooleanField(default=False, verbose_name="일본어 완성"),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_zh_complete",
            field=models.BooleanField(default=False, verbose_name="중국어 완성"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_es",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="스페인어 태그명"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_ja",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="일본어 태그명"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_zh",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="중국어 태그명"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name_es"], name="quiz_tag_name_es_bee2e2_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name_zh"], name="quiz_tag_name_zh_5f48b5_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name_ja"], name="quiz_tag_name_ja_130cab_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["is_es_complete"], name="quiz_tag_is_es_c_ed8171_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["is_zh_complete"], name="quiz_tag_is_zh_c_f5c70c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["is_ja_complete"], name="quiz_tag_is_ja_c_bbce1c_idx"
            ),
        ),
    ]
