# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0082_add_tag_multilingual_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_difficulty",
            field=models.IntegerField(
                default=5,
                help_text="시험의 난이도 (1: 쉬운 문제만, 10: 어려운 문제만, 5: 적절히 섞임)",
                validators=[MinValueValidator(1), MaxValueValidator(10)],
                verbose_name="시험 난이도",
                db_index=True,
            ),
        ),
    ]









