# Generated by Django 4.2.7 on 2025-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0083_add_exam_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_es",
            field=models.TextField(blank=True, verbose_name="스페인어 정답"),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_zh",
            field=models.TextField(blank=True, verbose_name="중국어 정답"),
        ),
        migrations.AddField(
            model_name="question",
            name="content_es",
            field=models.TextField(blank=True, verbose_name="스페인어 문제 내용"),
        ),
        migrations.AddField(
            model_name="question",
            name="content_zh",
            field=models.TextField(blank=True, verbose_name="중국어 문제 내용"),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_es",
            field=models.TextField(blank=True, null=True, verbose_name="스페인어 설명"),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_zh",
            field=models.TextField(blank=True, null=True, verbose_name="중국어 설명"),
        ),
        migrations.AddField(
            model_name="question",
            name="is_es_complete",
            field=models.BooleanField(default=False, verbose_name="스페인어 완성"),
        ),
        migrations.AddField(
            model_name="question",
            name="is_zh_complete",
            field=models.BooleanField(default=False, verbose_name="중국어 완성"),
        ),
        migrations.AddField(
            model_name="question",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="스페인어 제목"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="title_zh",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="중국어 제목"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["title_es"], name="quiz_questi_title_e_979d57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["title_zh"], name="quiz_questi_title_z_28308b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["content_es"], name="quiz_questi_content_5f0a4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["content_zh"], name="quiz_questi_content_ba84fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_es_complete"], name="quiz_questi_is_es_c_35a784_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_zh_complete"], name="quiz_questi_is_zh_c_4149b3_idx"
            ),
        ),
    ]
