# Generated by Django 4.2.7 on 2025-11-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0085_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="question",
            name="quiz_questi_title_e_979d57_idx",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="quiz_questi_title_z_28308b_idx",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="quiz_questi_content_5f0a4b_idx",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="quiz_questi_content_ba84fd_idx",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="quiz_questi_is_es_c_35a784_idx",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="quiz_questi_is_zh_c_4149b3_idx",
        ),
        migrations.AddField(
            model_name="exam",
            name="age_rating",
            field=models.CharField(
                choices=[("4+", "4+"), ("9+", "9+"), ("12+", "12+"), ("17+", "17+")],
                db_index=True,
                default="17+",
                help_text="시험 내용을 분석하여 추정된 연령 등급",
                max_length=10,
                verbose_name="연령 등급",
            ),
        ),
    ]
