# Generated by Django 4.2.7 on 2025-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0086_add_exam_age_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="studytask",
            name="is_es_complete",
            field=models.BooleanField(default=False, verbose_name="스페인어 완성"),
        ),
        migrations.AddField(
            model_name="studytask",
            name="is_ja_complete",
            field=models.BooleanField(default=False, verbose_name="일본어 완성"),
        ),
        migrations.AddField(
            model_name="studytask",
            name="is_zh_complete",
            field=models.BooleanField(default=False, verbose_name="중국어 완성"),
        ),
        migrations.AddField(
            model_name="studytask",
            name="name_es",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="스페인어 Task 이름"
            ),
        ),
        migrations.AddField(
            model_name="studytask",
            name="name_ja",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="일본어 Task 이름"
            ),
        ),
        migrations.AddField(
            model_name="studytask",
            name="name_zh",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="중국어 Task 이름"
            ),
        ),
        migrations.AddIndex(
            model_name="studytask",
            index=models.Index(
                fields=["is_es_complete"], name="quiz_studyt_is_es_c_5a1b05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studytask",
            index=models.Index(
                fields=["is_zh_complete"], name="quiz_studyt_is_zh_c_e10bf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studytask",
            index=models.Index(
                fields=["is_ja_complete"], name="quiz_studyt_is_ja_c_2490ce_idx"
            ),
        ),
    ]
