## Let's Encrypt Production ClusterIssuer
## 
## 실제 적용된 설정을 확인하려면:
##   kubectl get clusterissuer letsencrypt-prod -o yaml

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: topzone8713@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
