apiVersion: v1
kind: Pod
metadata:
  name: gradle-cache-loader
  namespace: jenkins
spec:
  restartPolicy: Never
  containers:
  - name: loader
    image: busybox:1.36
    command: ["/bin/sh", "-c", "sleep 86400"]
    resources:
      requests:
        memory: "4Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "1000m"
    volumeMounts:
    - name: gradle-cache
      mountPath: /cache
  volumes:
  - name: gradle-cache
    persistentVolumeClaim:
      claimName: gradle-cache-pvc