apiVersion: apps/v1
kind: Deployment
metadata:
  name: drillquiz
spec:
  selector:
    matchLabels:
      app: drillquiz
  replicas: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        org: tz
        team: devops
        environment: main
        app: drillquiz
    spec:
      imagePullSecrets:
        - name: tz-registrykey
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: node-role.kubernetes.io/control-plane
#                operator: DoesNotExist
      containers:
      - name: drillquiz
        image: doohee323/drillquiz:BUILD_NUMBER_PLACEHOLDER
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 2
            memory: 2000Mi
          requests:
            cpu: 1
            memory: 1000Mi
        envFrom:
        - configMapRef:
            name: drillquiz-configmap-GIT_BRANCH
        - secretRef:
            name: drillquiz-secret-GIT_BRANCH

---
apiVersion: v1
kind: Service
metadata:
  name: drillquiz
spec:
  type: NodePort
  selector:
    app: drillquiz
  ports:
    - port: 80
      name: api-80
      targetPort: 8000
#    - port: 443
#      name: api-443
#      targetPort: 443

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drillquiz-configmap-GIT_BRANCH
data:
  ENVIRONMENT: "production"
  USE_DOCKER: "true"
  POSTGRES_DB: "drillquiz"
  POSTGRES_USER: "admin"
  POSTGRES_HOST: "devops-postgres-postgresql.devops.svc.cluster.local"
  POSTGRES_PORT: "5432"
  SECRET_KEY: drillquiz-secret
  CURRENT_DOMAIN: "DOMAIN_PLACEHOLDER"
  ALLOWED_HOSTS: "localhost,127.0.0.1,devops.drillquiz.com,leetcode.drillquiz.com,DOMAIN_PLACEHOLDER"
  CORS_ALLOWED_ORIGINS: "http://localhost:8080,https://devops.drillquiz.com,https://leetcode.drillquiz.com,https://DOMAIN_PLACEHOLDER"
  USE_MINIO: "true"
  MINIO_ENDPOINT: "http://minio.devops.svc.cluster.local:9000"
  MINIO_BUCKET_NAME: "drillquiz"
  GOOGLE_OAUTH_CLIENT_ID: "195449497097-rf2f22ampv4imqb80fvibhr7oq5oc7km.apps.googleusercontent.com"
  GOOGLE_OAUTH_REDIRECT_URI: "https://us.drillquiz.com/api/google-oauth/"
  VUE_APP_GOOGLE_CLIENT_ID: "195449497097-rf2f22ampv4imqb80fvibhr7oq5oc7km.apps.googleusercontent.com"
  VUE_APP_GOOGLE_CLIENT_SECRET: #GOOGLE_OAUTH_CLIENT_SECRET
  VUE_APP_GOOGLE_REDIRECT_URI: "https://us.drillquiz.com/api/google-oauth/"
  APPLE_CLIENT_ID: "com.drillquiz.web"
  APPLE_TEAM_ID: "338MR492VK"
  CELERY_BROKER_URL: "redis://redis-cluster-drillquiz-master.devops.svc.cluster.local:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-cluster-drillquiz-master.devops.svc.cluster.local:6379/2"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drillquiz
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

    # Performance optimization
    nginx.ingress.kubernetes.io/enable-gzip: "true"
    nginx.ingress.kubernetes.io/gzip-types: "text/plain, text/css, application/json, application/javascript, text/xml, application/xml, application/xml+rss, text/javascript, application/xml"

    # Backend connection optimization
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"

    # Security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Referrer-Policy "strict-origin-when-cross-origin" always;
      
      # Content Security Policy - Allow Google Analytics 4 and OAuth
      add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://accounts.google.com; script-src-elem 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://accounts.google.com; connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://analytics.google.com https://accounts.google.com; img-src 'self' data: https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; font-src 'self' data: https://cdnjs.cloudflare.com;" always;
spec:
  ingressClassName: nginx
  rules:
  - host: DOMAIN_PLACEHOLDER
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: drillquiz
            port:
              number: 8000
  tls:
    - hosts:
        - DOMAIN_PLACEHOLDER
      secretName: drillquiz

---
apiVersion: v1
kind: Secret
metadata:
  name: drillquiz-secret-GIT_BRANCH
type: Opaque
data:
  SECRET_KEY: eW91ci1wcm9kdWN0aW9uLXNlY3JldC1rZXktaGVyZQ==
  POSTGRES_PASSWORD: #POSTGRES_PASSWORD
  MINIO_ACCESS_KEY: UnFyR1ZxR0hDaEExZHE4cGc4dUI=
  MINIO_SECRET_KEY: #MINIO_SECRET_KEY
  USE_MINIO: dHJ1ZQ==
  MINIO_BUCKET_NAME: ZHJpbGxxdWl6
  OPENAI_API_KEY: #OPENAI_API_KEY
  GOOGLE_OAUTH_CLIENT_SECRET: #GOOGLE_OAUTH_CLIENT_SECRET
  OPENAI_MODEL: Z3B0LTMuNS10dXJibw==
  GEMINI_API_KEY: #GEMINI_API_KEY
  GEMINI_MODEL: Z2VtaW5pLTIuNS1mbGFzaA==
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: drillquiz-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: drillquiz
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: drillquiz-ha
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: drillquiz
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 25

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drillquiz-celery-worker
spec:
  selector:
    matchLabels:
      app: drillquiz-celery-worker
  replicas: 2
  template:
    metadata:
      labels:
        org: tz
        team: devops
        environment: main
        app: drillquiz-celery-worker
    spec:
      imagePullSecrets:
        - name: tz-registrykey
      containers:
      - name: celery-worker
        image: doohee323/drillquiz:BUILD_NUMBER_PLACEHOLDER
        imagePullPolicy: Always
        command: ["celery", "-A", "drillquiz", "worker", "--loglevel=info", "--concurrency=2"]
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        envFrom:
        - configMapRef:
            name: drillquiz-configmap-GIT_BRANCH
        - secretRef:
            name: drillquiz-secret-GIT_BRANCH

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: drillquiz-celery-worker-ha
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: drillquiz-celery-worker
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50

